#!/usr/bin/perl
use local::lib;
use strict;
use warnings;
use v5.10;

use FindBin qw($RealBin);
use lib "$RealBin/lib";

BEGIN { $ENV{TZ} = 'UTC' }

use TimeTracker::Commands;

my $commands = TimeTracker::Commands->instance;

print "COMMANDS\n";
foreach my $handler (@{ $commands->handlers }) {
    next if $handler->help_short eq 'not implemented';
    print "\n", join("\n", @{ $handler->help_long }), "\n";
}
