#!/usr/bin/perl
use local::lib;
use strict;
use warnings;
use v5.10;

use FindBin qw($RealBin);
use lib "$RealBin/lib";

BEGIN { $ENV{TZ} = 'UTC' }

use TimeTracker::IRC ();

TimeTracker::IRC->start();
